# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{static_asset_descriptor}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Woodard"]
  s.date = %q{2010-06-18}
  s.description = %q{You can include page specific static assets and global static assets.  Use the layout and view generators}
  s.email = %q{sam.h.woodard@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/generators/layout/layout_generator.rb",
     "lib/generators/layout/templates/application.css.erb",
     "lib/generators/layout/templates/application.js.erb",
     "lib/generators/layout/templates/global_javascript.yml.erb",
     "lib/generators/layout/templates/global_stylesheet.yml.erb",
     "lib/generators/layout/templates/layout.html.erb",
     "lib/generators/view/templates/javascript.yml.erb",
     "lib/generators/view/templates/stylesheet.yml.erb",
     "lib/generators/view/templates/view.css.erb",
     "lib/generators/view/templates/view.html.erb",
     "lib/generators/view/templates/view.js.erb",
     "lib/generators/view/view_generator.rb",
     "lib/helpers.rb",
     "lib/static_descriptor_parser.rb",
     "test/static_asset_descriptor_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/shwoodard/static_asset_descriptor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Manages static includes in a rails app}
  s.test_files = [
    "test/static_asset_descriptor_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

